import Img1 from "../assets/women/women.png";
import Img2 from "../assets/women/women2.jpg";
import Img3 from "../assets/women/women3.jpg";
import Img4 from "../assets/women/women4.jpg";
import Img5 from "../assets/top/shirt.png";
import Img6 from "../assets/top/shirt2.png";
import Img7 from "../assets/top/shirt3.png";
import Review_img from "../assets/review_img.png";
import ProductImg from "./product_img";
import Trending from "../pages/Trending";


export const products_data = [
  {
    id: "1",
    title: "Elegant Evening Dress",
    price: 999,
    oldPrice: 1999,
    type: "women",
    trending: false,
    topProduct: false,
    bestSelling: false,
    description: "This stunning evening dress is perfect for any special occasion. Made from luxurious fabric, it features a flattering silhouette and exquisite detailing.",
    images: [Img1, Img2, Img3],
    img: 'https://www.libas.in/cdn/shop/files/1_4c57c998-1a9a-42ea-a937-31a2d9777988.jpg',
    sizes: ['XS', 'S', 'M', 'L'],
    rating: 5.0,
    color: "white",
    aosDelay: "0",
    reviews: [
      {
        name: "John Doe",
        review: "This dress is absolutely stunning! The fabric is soft and the fit is perfect. I received so many compliments at the party.",
        img: Review_img,
        stars: 5,
        rating: 4.8,
      },
      {
        name: "John Carter",
        review: "Loved the color and fit. Would buy again.",
        img: Review_img,
        stars: 4,
        rating: 4,
      },
      {
        name: "John Dom",
        review: "Good quality but delivery was late.",
        img: Review_img,
        stars: 3,
        rating: 3,
      },
    ],
  },
  {
    id: "2",
    title: "Elegant morning Dress",
    price: 2999,
    oldPrice: 12999,
    type: "women",
    trending: false,
    topProduct: false,
    bestSelling: false,
    description: "This stunning evening dress is perfect for any special occasion. Made from luxurious fabric, it features a flattering silhouette and exquisite detailing.",
    images: [Img1, Img2, Img3],
    img: Img2,
    sizes: ['M', 'L', 'XL'],
    rating: 4.5,
    color: "Red",
    aosDelay: "200",
    reviews: [
      {
        name: "John Doe",
        review: "This dress is absolutely stunning! The fabric is soft and the fit is perfect. I received so many compliments at the party.",
        img: Review_img,
        stars: 5,
        rating: 4.8,
      },
      {
        name: "John Carter",
        review: "Loved the color and fit. Would buy again.",
        img: Review_img,
        stars: 4,
        rating: 4,
      },
      {
        name: "John Dom",
        review: "Good quality but delivery was late.",
        img: Review_img,
        stars: 3,
        rating: 3,
      },
    ],
  },
  {
    id: "3",
    title: "Elegant Night Dress",
    price: 1999,
    oldPrice: 11999,
    type: "women",
    trending: false,
    topProduct: false,
    bestSelling: false,
    description: "This stunning evening dress is perfect for any special occasion. Made from luxurious fabric, it features a flattering silhouette and exquisite detailing.",
    images: [Img1, Img2, Img3],
    img: Img3,
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    rating: 4.7,
    color: "brown",
    aosDelay: "400",
    reviews: [
      {
        name: "John Doe",
        review: "This dress is absolutely stunning! The fabric is soft and the fit is perfect. I received so many compliments at the party.",
        img: Review_img,
        stars: "★★★★★",
        rating: 4.8,
      },
      {
        name: "John Carter",
        review: "Loved the color and fit. Would buy again.",
        img: Review_img,
        stars: "★★★★",
        rating: 4,
      },
      {
        name: "John Dom",
        review: "Good quality but delivery was late.",
        img: Review_img,
        stars: "★★★",
        rating: 3,
      },
    ],
  },
  {
    id: "4",
    title: "Elegant Party Dress",
    price: 5999,
    oldPrice: 15999,
    type: "women",
    trending: false,
    topProduct: false,
    bestSelling: false,
    description: "This stunning evening dress is perfect for any special occasion. Made from luxurious fabric, it features a flattering silhouette and exquisite detailing.",
    images: [Img1, Img2, Img3, Img4],
    img: Img4,
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    rating: 4.4,
    color: "Yellow",
    aosDelay: "600",
    reviews: [
      {
        name: "John Doe",
        review: "This dress is absolutely stunning! The fabric is soft and the fit is perfect. I received so many compliments at the party.",
        img: Review_img,
        stars: 5,
        rating: 4.8,
      },
      {
        name: "John Carter",
        review: "Loved the color and fit. Would buy again.",
        img: Review_img,
        stars: 4,
        rating: 4,
      },
      {
        name: "John Dom",
        review: "Good quality but delivery was late.",
        img: Review_img,
        stars: 3,
        rating: 3,
      },
    ],
  },
  {
    id: "5",
    title: "Fashin T-Shirt",
    price: 5999,
    oldPrice: 15999,
    type: "women",
    topRated: false,
    trending: true,
    description: "This stunning evening dress is perfect for any special occasion. Made from luxurious fabric, it features a flattering silhouette and exquisite detailing.",
    images: [Img1, Img2, Img3, Img4],
    img: Img4,
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    rating: 4.5,
    color: "Pink",
    aosDelay: "800",
    reviews: [
      {
        name: "John Doe",
        review: "This dress is absolutely stunning! The fabric is soft and the fit is perfect. I received so many compliments at the party.",
        img: Review_img,
        stars: 5,
        rating: 4.8,
      },
      {
        name: "John Carter",
        review: "Loved the color and fit. Would buy again.",
        img: Review_img,
        stars: 4,
        rating: 4,
      },
      {
        name: "John Dom",
        review: "Good quality but delivery was late.",
        img: Review_img,
        stars: 3,
        rating: 3,
      },
    ],
  },
  // Add more products here...
  {
    id: "6",
    title: "Women's High-Waisted Jeans",
    price: 2199,
    oldPrice: 4299,
    type: "women",
    topRated: false,
    trending: true,
    description: "Flattering high-waisted jeans with a straight-leg cut. Crafted from premium stretch denim for ultimate comfort and style.",
    img: "https://picsum.photos/seed/picsum16/400/500",
    images: [
      "https://picsum.photos/seed/picsum16/400/500",
      "https://picsum.photos/seed/picsum17/400/500",
      "https://picsum.photos/seed/picsum18/400/500",
    ],
    sizes: ['26', '28', '30', '32'],
    rating: 4.8,
    color: "Black",
    category: "Women",
    aosDelay: "0",
    reviews: [
      { name: "Kavita Desai", review: "The fit is amazing and they are so comfortable to wear all day.", img: "https://i.pravatar.cc/48?u=Kavita", rating: 5 },
      { name: "Isha Reddy", review: "Finally found the perfect pair of black jeans!", img: "https://i.pravatar.cc/48?u=Isha", rating: 5 },
    ],
  },


  // Mens 
  {
    id: "7",
    title: "Men's Polo T-Shirt",
    price: 1199,
    oldPrice: 2399,
    type: "men",
    trending: false,
    topProduct: false,
    bestSelling: false,
    description: "A smart and classic polo t-shirt made from breathable pique cotton. A versatile piece for any man's wardrobe.",
    img: "https://picsum.photos/seed/picsum19/400/500",
    images: [
      "https://picsum.photos/seed/picsum19/400/500",
      "https://picsum.photos/seed/picsum20/400/500",
      "https://picsum.photos/seed/picsum21/400/500",
    ],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    rating: 4.7,
    color: "Navy Blue",
    category: "Men",
    aosDelay: "200",
    reviews: [
      { name: "Rahul Bajaj", review: "Great fabric and fit. Looks very premium.", img: "https://i.pravatar.cc/48?u=Rahul", rating: 5 },
    ],
  },
  {
    id: "8",
    title: "Men's Summer Dress",
    price: 1799,
    oldPrice: 3599,
    type: "men",
    topRated: false,
    trending: true,
    description: "A breezy and stylish summer dress perfect for casual outings or beach days.",
    img: "https://picsum.photos/seed/picsum22/400/500",
    images: [
      "https://picsum.photos/seed/picsum22/400/500",
      "https://picsum.photos/seed/picsum23/400/500",
      "https://picsum.photos/seed/picsum24/400/500",
    ],
    sizes: ['XS', 'S', 'M', 'L'],
    rating: 4.6,
    color: "Floral Print",
    category: "men",
    aosDelay: "400",
    reviews: [
      { name: "Priya Sharma", review: "Love the light fabric and vibrant print!", img: "https://i.pravatar.cc/48?u=Priya", rating: 5 },
      { name: "Anjali Verma", review: "Perfect for summer. Got many compliments.", img: "https://i.pravatar.cc/48?u=Anjali", rating: 4 },
    ],
  },

  // kids 

  {
    id: "12",
    title: "kids Ethnic",
    price: 999,
    oldPrice: 1999,
    type: "kids",
    trending: false,
    topProduct: false,
    bestSelling: false,
    description: "This stunning evening dress is perfect for any special occasion. Made from luxurious fabric, it features a flattering silhouette and exquisite detailing.",
    images: [Img1, Img2, Img3],
    img: 'https://www.libas.in/cdn/shop/files/1_4c57c998-1a9a-42ea-a937-31a2d9777988.jpg',
    sizes: ['XS', 'S', 'M', 'L'],
    rating: 5.0,
    color: "white",
    reviews: [
      {
        name: "John Doe",
        review: "This dress is absolutely stunning! The fabric is soft and the fit is perfect. I received so many compliments at the party.",
        img: Review_img,
        stars: 5,
        rating: 4.8,
      },
      {
        name: "John Carter",
        review: "Loved the color and fit. Would buy again.",
        img: Review_img,
        stars: 4,
        rating: 4,
      },
      {
        name: "John Dom",
        review: "Good quality but delivery was late.",
        img: Review_img,
        stars: 3,
        rating: 3,
      },
    ],
    aosDelay: "0",

  },
  {
    id: "9",
    title: "kids western",
    price: 999,
    oldPrice: 1999,
    type: "kids",
    trending: false,
    topProduct: false,
    bestSelling: false,
    description: "This stunning evening dress is perfect for any special occasion. Made from luxurious fabric, it features a flattering silhouette and exquisite detailing.",
    images: [Img1, Img2, Img3],
    img: 'https://www.libas.in/cdn/shop/files/1_4c57c998-1a9a-42ea-a937-31a2d9777988.jpg',
    sizes: ['XS', 'S', 'M', 'L'],
    rating: 4.5,
    color: "Red",
    reviews: [
      {
        name: "John Doe",
        review: "This dress is absolutely stunning! The fabric is soft and the fit is perfect. I received so many compliments at the party.",
        img: Review_img,
        stars: 5,
        rating: 4.8,
      },
      {
        name: "John Carter",
        review: "Loved the color and fit. Would buy again.",
        img: Review_img,
        stars: 4,
        rating: 4,
      },
      {
        name: "John Dom",
        review: "Good quality but delivery was late.",
        img: Review_img,
        stars: 3,
        rating: 3,
      },
    ],
    aosDelay: "200",

  },
  {
    id: "10",
    title: "Goggles",
    price: 999,
    oldPrice: 1999,
    type: "kids",
    trending: false,
    topProduct: false,
    bestSelling: false,
    description: "This stunning evening dress is perfect for any special occasion. Made from luxurious fabric, it features a flattering silhouette and exquisite detailing.",
    images: [Img1, Img2, Img3],
    img: 'https://img.faballey.com/images/Product/IGS00062Z/d3.jpg',
    sizes: ['XS', 'S', 'M', 'L'],
    rating: 4.7,
    color: "brown",
    reviews: [
      {
        name: "John Doe",
        review: "This dress is absolutely stunning! The fabric is soft and the fit is perfect. I received so many compliments at the party.",
        img: Review_img,
        stars: 5,
        rating: 4.8,
      },
      {
        name: "John Carter",
        review: "Loved the color and fit. Would buy again.",
        img: Review_img,
        stars: 4,
        rating: 4,
      },
      {
        name: "John Dom",
        review: "Good quality but delivery was late.",
        img: Review_img,
        stars: 3,
        rating: 3,
      },
    ],
    aosDelay: "400",

  },
  {
    id: "11",
    title: "Printed T-Shirt",
    price: 999,
    oldPrice: 1999,
    type: "kids",
    trending: false,
    topProduct: false,
    bestSelling: false,
    description: "This stunning evening dress is perfect for any special occasion. Made from luxurious fabric, it features a flattering silhouette and exquisite detailing.",
    images: [Img1, Img2, Img3],
    img: 'https://assets.myntassets.com/dpr_1.5,q_30,w_400,c_limit,fl_progressive/assets/images/2025/JUNE/7/Que0gpup_84255218cd5b4b2b978da411a826d34f.jpg',
    sizes: ['XS', 'S', 'M', 'L'],
    rating: 4.4,
    color: "Yellow",
    reviews: [
      {
        name: "John Doe",
        review: "This dress is absolutely stunning! The fabric is soft and the fit is perfect. I received so many compliments at the party.",
        img: Review_img,
        stars: 5,
        rating: 4.8,
      },
      {
        name: "John Carter",
        review: "Loved the color and fit. Would buy again.",
        img: Review_img,
        stars: 4,
        rating: 4,
      },
      {
        name: "John Dom",
        review: "Good quality but delivery was late.",
        img: Review_img,
        stars: 3,
        rating: 3,
      },
    ],
    aosDelay: "600",

  },
  {
    id: "13",
    title: "Fashin T-Shirt",
    price: 999,
    oldPrice: 1999,
    type: "kids",
    trending: false,
    topProduct: false,
    bestSelling: false,
    description: "This stunning evening dress is perfect for any special occasion. Made from luxurious fabric, it features a flattering silhouette and exquisite detailing.",
    images: [Img1, Img2, Img3],
    img: 'https://i.pinimg.com/736x/67/b8/df/67b8dfe76133d78fc8a90d2611a742d9.jpg',
    sizes: ['XS', 'S', 'M', 'L'],
    rating: 4.5,
    color: "Pink",
    reviews: [
      {
        name: "John Doe",
        review: "This dress is absolutely stunning! The fabric is soft and the fit is perfect. I received so many compliments at the party.",
        img: Review_img,
        stars: 5,
        rating: 4.8,
      },
      {
        name: "John Carter",
        review: "Loved the color and fit. Would buy again.",
        img: Review_img,
        stars: 4,
        rating: 4,
      },
      {
        name: "John Dom",
        review: "Good quality but delivery was late.",
        img: Review_img,
        stars: 3,
        rating: 3,
      },
    ],
    aosDelay: "800",

  },

  {
    id: "14",
    img: Img5,
    title: "Casual Wear",
    description:
      "lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    price: 999,
    oldPrice: 1999,
    type: "product",
    trending: false,
    topProduct: true,
    bestSelling: true,
    description: "This stunning evening dress is perfect for any special occasion. Made from luxurious fabric, it features a flattering silhouette and exquisite detailing.",
    images: [Img1, Img2, Img3],
    sizes: ['XS', 'S', 'M', 'L'],
    rating: 4.5,
    color: "Pink",
    reviews: [
      {
        name: "John Doe",
        review: "This dress is absolutely stunning! The fabric is soft and the fit is perfect. I received so many compliments at the party.",
        img: Review_img,
        stars: 5,
        rating: 4.8,
      },
      {
        name: "John Carter",
        review: "Loved the color and fit. Would buy again.",
        img: Review_img,
        stars: 4,
        rating: 4,
      },
      {
        name: "John Dom",
        review: "Good quality but delivery was late.",
        img: Review_img,
        stars: 3,
        rating: 3,
      },
    ],
    aosDelay: "800",

  },
  {
    id: "15",
    img: Img6,
    title: "Printed shirt",
    description:
      "lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    price: 999,
    oldPrice: 1999,
    type: "product",
    trending: false,
    topProduct: true,
    bestSelling: true,
    description: "This stunning evening dress is perfect for any special occasion. Made from luxurious fabric, it features a flattering silhouette and exquisite detailing.",
    images: [Img1, Img2, Img3],
    sizes: ['XS', 'S', 'M', 'L'],
    rating: 4.5,
    color: "Pink",
    reviews: [
      {
        name: "John Doe",
        review: "This dress is absolutely stunning! The fabric is soft and the fit is perfect. I received so many compliments at the party.",
        img: Review_img,
        stars: 5,
        rating: 4.8,
      },
      {
        name: "John Carter",
        review: "Loved the color and fit. Would buy again.",
        img: Review_img,
        stars: 4,
        rating: 4,
      },
      {
        name: "John Dom",
        review: "Good quality but delivery was late.",
        img: Review_img,
        stars: 3,
        rating: 3,
      },
    ],
    aosDelay: "800",

  },
  {
    id: "16",
    img: Img7,
    title: "Women shirt",
    description:
      "lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    price: 999,
    oldPrice: 1999,
    type: "product",
    trending: false,
    topProduct: true,
    bestSelling: false,
    description: "This stunning evening dress is perfect for any special occasion. Made from luxurious fabric, it features a flattering silhouette and exquisite detailing.",
    images: [Img1, Img2, Img3],
    sizes: ['XS', 'S', 'M', 'L'],
    rating: 4.5,
    color: "Pink",
    reviews: [
      {
        name: "John Doe",
        review: "This dress is absolutely stunning! The fabric is soft and the fit is perfect. I received so many compliments at the party.",
        img: Review_img,
        stars: 5,
        rating: 4.8,
      },
      {
        name: "John Carter",
        review: "Loved the color and fit. Would buy again.",
        img: Review_img,
        stars: 4,
        rating: 4,
      },
      {
        name: "John Dom",
        review: "Good quality but delivery was late.",
        img: Review_img,
        stars: 3,
        rating: 3,
      },
    ],
    aosDelay: "800",

  }
];